version: '3.8'

services:
  bigods-app:
    container_name: bigods-app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=bigods-mysql
      - DB_PORT=3306
      - DB_DATABASE=bigods
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - APP_URL=http://192.168.15.28:8000
    depends_on:
      - bigods-mysql
      - bigods-redis
    networks:
      - laravel-network

  bigods-mysql:
    container_name: bigods-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bigods
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  bigods-redis:
    container_name: bigods-redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - laravel-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:

networks:
  laravel-network:
    driver: bridge
